### ISSUE TITLE
Fix WinForms high dpi issues

### ISSUE THREAD

**Issue by devkeydet** [devkeydet/migrate2cds#4]
https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

**Comment by devkeydet** [comment]
WORKAROUND UNTIL FIXED: run on non high dpi.  Easiest way is on an Azure VM @ 1080p.

**Comment by jamesnovak** [comment]
this seems to only occur because of the WPF form being launched.  This has not been an issue with the XrmToolBox hosted control
